### ISSUE TITLE
Latest image for v1.21.2 doesn't seem to be working

### ISSUE THREAD

**Issue by pragmaticivan** [kbst/kind-eks-d#13]
image: `ghcr.io/kbst/kind-eks-d:v1.21.2-kbst.0`

I can confirm `ghcr.io/kbst/kind-eks-d:v1.18.9-kbst.1` works.

Appling with CTLPTL Dev (https://github.com/tilt-dev/ctlptl) - It uses kind CLI.
```
# Creates a kind cluster with a registry.
apiVersion: ctlptl.dev/v1alpha1
kind: Cluster
product: kind
registry: ctlptl-registry
minCPUs: 4
kindV1Alpha4Cluster:
  name: eks-d-cluster
  nodes:
  - role: control-plane
    image: ghcr.io/kbst/kind-eks-d:v1.21.2-kbst.0
  - role: worker
    image: ghcr.io/kbst/kind-eks-d:v1.21.2-kbst.0
```
